import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/sthe.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.03, -0.11, 0]} rotation={[0, 0.08, 0]}>
          <group
            position={[-0.02, 2.56, 0]}
            rotation={[0, -0.08, 0]}
            scale={0.92}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_1.geometry}
              material={nodes.Cylinder_1.material}
              position={[0, 0.31, 0]}
              scale={[1, 0.79, 1]}
            />
          </group>
          <group position={[-15.55, 0, 0]}>
            <group
              position={[15.52, 0.07, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={63.77}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.new_one_model_mesh4Boss_Extrude3Shape.geometry}
                material={nodes.new_one_model_mesh4Boss_Extrude3Shape.material}
              />
            </group>
            <group
              position={[15.52, 0.07, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={63.77}
            >
              <group rotation={[Math.PI / 2, -0.08, 0]} scale={0.02}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.polySurfaceShape1.geometry}
                  material={nodes.polySurfaceShape1.material}
                />
              </group>
            </group>
            <group
              position={[15.52, 0.07, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={63.77}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.new_one_model_mesh2Cut_Extrude2Shape.geometry}
                material={nodes.new_one_model_mesh2Cut_Extrude2Shape.material}
              />
            </group>
            <group
              position={[15.52, 0.07, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={63.77}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.new_one_model_mesh1new_onShape.geometry}
                material={nodes.new_one_model_mesh1new_onShape.material}
              />
            </group>
          </group>
          <group position={[-15.99, 0.61, -2.07]} scale={0.37}>
            <group
              position={[1.72, 1.47, -3.57]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={[1.44, 1.07, 1.16]}
            >
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape1.geometry}
                  material={nodes.pasted__BodyShape1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape2.geometry}
                  material={nodes.pasted__BodyShape2.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape3.geometry}
                  material={nodes.pasted__BodyShape3.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape4.geometry}
                  material={nodes.pasted__BodyShape4.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape5.geometry}
                  material={nodes.pasted__BodyShape5.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape6.geometry}
                  material={nodes.pasted__BodyShape6.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape7.geometry}
                  material={nodes.pasted__BodyShape7.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape8.geometry}
                  material={nodes.pasted__BodyShape8.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape9.geometry}
                  material={nodes.pasted__BodyShape9.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape10.geometry}
                  material={nodes.pasted__BodyShape10.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape11.geometry}
                  material={nodes.pasted__BodyShape11.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape12.geometry}
                  material={nodes.pasted__BodyShape12.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape13.geometry}
                  material={nodes.pasted__BodyShape13.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape14.geometry}
                  material={nodes.pasted__BodyShape14.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape15.geometry}
                  material={nodes.pasted__BodyShape15.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape16.geometry}
                  material={nodes.pasted__BodyShape16.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape17.geometry}
                  material={nodes.pasted__BodyShape17.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape18.geometry}
                  material={nodes.pasted__BodyShape18.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape19.geometry}
                  material={nodes.pasted__BodyShape19.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape20.geometry}
                  material={nodes.pasted__BodyShape20.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape21.geometry}
                  material={nodes.pasted__BodyShape21.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape22.geometry}
                  material={nodes.pasted__BodyShape22.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape23.geometry}
                  material={nodes.pasted__BodyShape23.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape24.geometry}
                  material={nodes.pasted__BodyShape24.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape25.geometry}
                  material={nodes.pasted__BodyShape25.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape26.geometry}
                  material={nodes.pasted__BodyShape26.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape27.geometry}
                  material={nodes.pasted__BodyShape27.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape28.geometry}
                  material={nodes.pasted__BodyShape28.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape29.geometry}
                  material={nodes.pasted__BodyShape29.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape30.geometry}
                  material={nodes.pasted__BodyShape30.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape31.geometry}
                  material={nodes.pasted__BodyShape31.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape32.geometry}
                  material={nodes.pasted__BodyShape32.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape33.geometry}
                  material={nodes.pasted__BodyShape33.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape34.geometry}
                  material={nodes.pasted__BodyShape34.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape35.geometry}
                  material={nodes.pasted__BodyShape35.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape36.geometry}
                  material={nodes.pasted__BodyShape36.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape37.geometry}
                  material={nodes.pasted__BodyShape37.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape38.geometry}
                  material={nodes.pasted__BodyShape38.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape39.geometry}
                  material={nodes.pasted__BodyShape39.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape40.geometry}
                  material={nodes.pasted__BodyShape40.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape41.geometry}
                  material={nodes.pasted__BodyShape41.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape42.geometry}
                  material={nodes.pasted__BodyShape42.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape43.geometry}
                  material={nodes.pasted__BodyShape43.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape44.geometry}
                  material={nodes.pasted__BodyShape44.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape45.geometry}
                  material={nodes.pasted__BodyShape45.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape46.geometry}
                  material={nodes.pasted__BodyShape46.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape47.geometry}
                  material={nodes.pasted__BodyShape47.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape48.geometry}
                  material={nodes.pasted__BodyShape48.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape49.geometry}
                  material={nodes.pasted__BodyShape49.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape50.geometry}
                  material={nodes.pasted__BodyShape50.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape51.geometry}
                  material={nodes.pasted__BodyShape51.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape52.geometry}
                  material={nodes.pasted__BodyShape52.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape53.geometry}
                  material={nodes.pasted__BodyShape53.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape54.geometry}
                  material={nodes.pasted__BodyShape54.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape55.geometry}
                  material={nodes.pasted__BodyShape55.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape56.geometry}
                  material={nodes.pasted__BodyShape56.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape57.geometry}
                  material={nodes.pasted__BodyShape57.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape58.geometry}
                  material={nodes.pasted__BodyShape58.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape59.geometry}
                  material={nodes.pasted__BodyShape59.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape60.geometry}
                  material={nodes.pasted__BodyShape60.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape61.geometry}
                  material={nodes.pasted__BodyShape61.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape62.geometry}
                  material={nodes.pasted__BodyShape62.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape63.geometry}
                  material={nodes.pasted__BodyShape63.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape64.geometry}
                  material={nodes.pasted__BodyShape64.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape65.geometry}
                  material={nodes.pasted__BodyShape65.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape66.geometry}
                  material={nodes.pasted__BodyShape66.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape67.geometry}
                  material={nodes.pasted__BodyShape67.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape68.geometry}
                  material={nodes.pasted__BodyShape68.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape69.geometry}
                  material={nodes.pasted__BodyShape69.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape70.geometry}
                  material={nodes.pasted__BodyShape70.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape71.geometry}
                  material={nodes.pasted__BodyShape71.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape72.geometry}
                  material={nodes.pasted__BodyShape72.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape73.geometry}
                  material={nodes.pasted__BodyShape73.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape74.geometry}
                  material={nodes.pasted__BodyShape74.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape75.geometry}
                  material={nodes.pasted__BodyShape75.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape76.geometry}
                  material={nodes.pasted__BodyShape76.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape77.geometry}
                  material={nodes.pasted__BodyShape77.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape78.geometry}
                  material={nodes.pasted__BodyShape78.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape79.geometry}
                  material={nodes.pasted__BodyShape79.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape80.geometry}
                  material={nodes.pasted__BodyShape80.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape81.geometry}
                  material={nodes.pasted__BodyShape81.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape82.geometry}
                  material={nodes.pasted__BodyShape82.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape83.geometry}
                  material={nodes.pasted__BodyShape83.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape84.geometry}
                  material={nodes.pasted__BodyShape84.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape85.geometry}
                  material={nodes.pasted__BodyShape85.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape86.geometry}
                  material={nodes.pasted__BodyShape86.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape87.geometry}
                  material={nodes.pasted__BodyShape87.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape88.geometry}
                  material={nodes.pasted__BodyShape88.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape89.geometry}
                  material={nodes.pasted__BodyShape89.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape90.geometry}
                  material={nodes.pasted__BodyShape90.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape91.geometry}
                  material={nodes.pasted__BodyShape91.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape92.geometry}
                  material={nodes.pasted__BodyShape92.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape93.geometry}
                  material={nodes.pasted__BodyShape93.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape94.geometry}
                  material={nodes.pasted__BodyShape94.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape95.geometry}
                  material={nodes.pasted__BodyShape95.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape96.geometry}
                  material={nodes.pasted__BodyShape96.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape97.geometry}
                  material={nodes.pasted__BodyShape97.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape98.geometry}
                  material={nodes.pasted__BodyShape98.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape99.geometry}
                  material={nodes.pasted__BodyShape99.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape100.geometry}
                  material={nodes.pasted__BodyShape100.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape101.geometry}
                  material={nodes.pasted__BodyShape101.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape102.geometry}
                  material={nodes.pasted__BodyShape102.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape103.geometry}
                  material={nodes.pasted__BodyShape103.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape104.geometry}
                  material={nodes.pasted__BodyShape104.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape105.geometry}
                  material={nodes.pasted__BodyShape105.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape106.geometry}
                  material={nodes.pasted__BodyShape106.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape107.geometry}
                  material={nodes.pasted__BodyShape107.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape108.geometry}
                  material={nodes.pasted__BodyShape108.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape109.geometry}
                  material={nodes.pasted__BodyShape109.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape110.geometry}
                  material={nodes.pasted__BodyShape110.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape111.geometry}
                  material={nodes.pasted__BodyShape111.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape112.geometry}
                  material={nodes.pasted__BodyShape112.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape113.geometry}
                  material={nodes.pasted__BodyShape113.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape114.geometry}
                  material={nodes.pasted__BodyShape114.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape115.geometry}
                  material={nodes.pasted__BodyShape115.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape116.geometry}
                  material={nodes.pasted__BodyShape116.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape117.geometry}
                  material={nodes.pasted__BodyShape117.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape118.geometry}
                  material={nodes.pasted__BodyShape118.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape119.geometry}
                  material={nodes.pasted__BodyShape119.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape120.geometry}
                  material={nodes.pasted__BodyShape120.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape121.geometry}
                  material={nodes.pasted__BodyShape121.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape122.geometry}
                  material={nodes.pasted__BodyShape122.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape123.geometry}
                  material={nodes.pasted__BodyShape123.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape124.geometry}
                  material={nodes.pasted__BodyShape124.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape125.geometry}
                  material={nodes.pasted__BodyShape125.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape126.geometry}
                  material={nodes.pasted__BodyShape126.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape127.geometry}
                  material={nodes.pasted__BodyShape127.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape128.geometry}
                  material={nodes.pasted__BodyShape128.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape129.geometry}
                  material={nodes.pasted__BodyShape129.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape130.geometry}
                  material={nodes.pasted__BodyShape130.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape131.geometry}
                  material={nodes.pasted__BodyShape131.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape132.geometry}
                  material={nodes.pasted__BodyShape132.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape133.geometry}
                  material={nodes.pasted__BodyShape133.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape134.geometry}
                  material={nodes.pasted__BodyShape134.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape135.geometry}
                  material={nodes.pasted__BodyShape135.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape136.geometry}
                  material={nodes.pasted__BodyShape136.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape138.geometry}
                  material={nodes.pasted__BodyShape138.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape139.geometry}
                  material={nodes.pasted__BodyShape139.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape140.geometry}
                  material={nodes.pasted__BodyShape140.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape141.geometry}
                  material={nodes.pasted__BodyShape141.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape142.geometry}
                  material={nodes.pasted__BodyShape142.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape143.geometry}
                  material={nodes.pasted__BodyShape143.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape144.geometry}
                  material={nodes.pasted__BodyShape144.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape145.geometry}
                  material={nodes.pasted__BodyShape145.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape146.geometry}
                  material={nodes.pasted__BodyShape146.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape147.geometry}
                  material={nodes.pasted__BodyShape147.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape148.geometry}
                  material={nodes.pasted__BodyShape148.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape149.geometry}
                  material={nodes.pasted__BodyShape149.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape150.geometry}
                  material={nodes.pasted__BodyShape150.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape151.geometry}
                  material={nodes.pasted__BodyShape151.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape152.geometry}
                  material={nodes.pasted__BodyShape152.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape153.geometry}
                  material={nodes.pasted__BodyShape153.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape154.geometry}
                  material={nodes.pasted__BodyShape154.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape155.geometry}
                  material={nodes.pasted__BodyShape155.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape156.geometry}
                  material={nodes.pasted__BodyShape156.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape157.geometry}
                  material={nodes.pasted__BodyShape157.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape158.geometry}
                  material={nodes.pasted__BodyShape158.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape159.geometry}
                  material={nodes.pasted__BodyShape159.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape160.geometry}
                  material={nodes.pasted__BodyShape160.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape161.geometry}
                  material={nodes.pasted__BodyShape161.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape162.geometry}
                  material={nodes.pasted__BodyShape162.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape163.geometry}
                  material={nodes.pasted__BodyShape163.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape164.geometry}
                  material={nodes.pasted__BodyShape164.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape165.geometry}
                  material={nodes.pasted__BodyShape165.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape166.geometry}
                  material={nodes.pasted__BodyShape166.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape137.geometry}
                  material={nodes.pasted__BodyShape137.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape2_1.geometry}
                  material={nodes.pasted__BodyShape2_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape167.geometry}
                  material={nodes.pasted__BodyShape167.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape168.geometry}
                  material={nodes.pasted__BodyShape168.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape169.geometry}
                  material={nodes.pasted__BodyShape169.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape170.geometry}
                  material={nodes.pasted__BodyShape170.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape171.geometry}
                  material={nodes.pasted__BodyShape171.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape5_1.geometry}
                  material={nodes.pasted__BodyShape5_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape172.geometry}
                  material={nodes.pasted__BodyShape172.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape173.geometry}
                  material={nodes.pasted__BodyShape173.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape174.geometry}
                  material={nodes.pasted__BodyShape174.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape175.geometry}
                  material={nodes.pasted__BodyShape175.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape176.geometry}
                  material={nodes.pasted__BodyShape176.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape177.geometry}
                  material={nodes.pasted__BodyShape177.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape178.geometry}
                  material={nodes.pasted__BodyShape178.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape179.geometry}
                  material={nodes.pasted__BodyShape179.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape180.geometry}
                  material={nodes.pasted__BodyShape180.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape181.geometry}
                  material={nodes.pasted__BodyShape181.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape182.geometry}
                  material={nodes.pasted__BodyShape182.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape6_1.geometry}
                  material={nodes.pasted__BodyShape6_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape183.geometry}
                  material={nodes.pasted__BodyShape183.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape184.geometry}
                  material={nodes.pasted__BodyShape184.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape185.geometry}
                  material={nodes.pasted__BodyShape185.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape186.geometry}
                  material={nodes.pasted__BodyShape186.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape187.geometry}
                  material={nodes.pasted__BodyShape187.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape7_1.geometry}
                  material={nodes.pasted__BodyShape7_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape188.geometry}
                  material={nodes.pasted__BodyShape188.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape189.geometry}
                  material={nodes.pasted__BodyShape189.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape190.geometry}
                  material={nodes.pasted__BodyShape190.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape191.geometry}
                  material={nodes.pasted__BodyShape191.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape192.geometry}
                  material={nodes.pasted__BodyShape192.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape8_1.geometry}
                  material={nodes.pasted__BodyShape8_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape193.geometry}
                  material={nodes.pasted__BodyShape193.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape194.geometry}
                  material={nodes.pasted__BodyShape194.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape195.geometry}
                  material={nodes.pasted__BodyShape195.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape196.geometry}
                  material={nodes.pasted__BodyShape196.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape197.geometry}
                  material={nodes.pasted__BodyShape197.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape9_1.geometry}
                  material={nodes.pasted__BodyShape9_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape198.geometry}
                  material={nodes.pasted__BodyShape198.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape199.geometry}
                  material={nodes.pasted__BodyShape199.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape200.geometry}
                  material={nodes.pasted__BodyShape200.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape201.geometry}
                  material={nodes.pasted__BodyShape201.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape202.geometry}
                  material={nodes.pasted__BodyShape202.material}
                />
              </group>
              <group position={[-29.19, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape10_1.geometry}
                  material={nodes.pasted__BodyShape10_1.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape203.geometry}
                  material={nodes.pasted__BodyShape203.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape204.geometry}
                  material={nodes.pasted__BodyShape204.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape205.geometry}
                  material={nodes.pasted__BodyShape205.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape206.geometry}
                  material={nodes.pasted__BodyShape206.material}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pasted__BodyShape207.geometry}
                  material={nodes.pasted__BodyShape207.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[0, 3.44, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={147.48}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh1Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_1Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh1Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_1Shape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh2Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_2Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh2Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_2Shape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh3Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_3Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh3Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_3Shape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh4Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_4Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh4Arduino_Pro_Mini_step_1_PCBComponent_step_1_0_1uF_step_4Shape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh5Arduino_Pro_Mini_step_1_PCBComponent_step_1_Board_step_1Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh5Arduino_Pro_Mini_step_1_PCBComponent_step_1_Board_step_1Shape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Arduino_Pro_Mini_mesh6Arduino_Pro_Mini_stepShape.geometry
              }
              material={
                nodes.Arduino_Pro_Mini_mesh6Arduino_Pro_Mini_stepShape.material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Arduino_Pro_Mini_mesh7Arduino_Pro_Mini_stepfaceShape
                  .geometry
              }
              material={
                nodes.Arduino_Pro_Mini_mesh7Arduino_Pro_Mini_stepfaceShape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh8Arduino_Pro_Mini_step_1_PCBComponent_step_1_1X02_step_1Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh8Arduino_Pro_Mini_step_1_PCBComponent_step_1_1X02_step_1Shape
                  .material
              }
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes
                  .Arduino_Pro_Mini_mesh9Arduino_Pro_Mini_step_1_PCBComponent_step_1_330_step_1Shape
                  .geometry
              }
              material={
                nodes
                  .Arduino_Pro_Mini_mesh9Arduino_Pro_Mini_step_1_PCBComponent_step_1_330_step_1Shape
                  .material
              }
            />
          </group>
          <group position={[0, -2.82, 0]}>
            <group position={[0, 6.61, 0]} scale={[3.05, 0.21, 3.05]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pCubeShape1.geometry}
                material={nodes.pCubeShape1.material}
              />
            </group>
          </group>
          <group position={[0, 0.26, 0]}>
            <group position={[0.73, -3.16, 1.83]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.bevelPolygon1Shape.geometry}
                material={nodes.bevelPolygon1Shape.material}
                position={[-0.14, 0, -0.12]}
              />
            </group>
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={nodes.Cylinder.material}
            position={[-0.03, 1.1, 0]}
            rotation={[0, -0.08, 0]}
            scale={[6.81, 0.14, 6.81]}
          />
        </group>
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={33.13}
        near={21.37}
        fov={39.6}
        position={[-10.5, 8.74, -25.18]}
        rotation={[-2.93, -0.35, -3.07]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={33.13}
        near={21.37}
        fov={39.6}
        position={[-10.5, 8.74, -25.18]}
        rotation={[-2.93, -0.35, -3.07]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={40.84}
        near={28.87}
        fov={54.43}
        position={[12.51, 11.08, -32.22]}
        rotation={[-2.92, 0.37, 3.06]}
      />
    </group>
  );
}

useGLTF.preload("/sthe.glb");
