/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default  function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/planew.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
         <group rotation={[Math.PI / 2, 0, 0]} >
      <group name="Scene">
        <group name="polySurface78" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform48" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface77" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform46" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface76" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform47" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface75" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform45" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface74" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform27" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface73" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform44" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface72" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform30" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface71" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform99" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface70" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform26" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface69" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform97" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface68" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform15" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface67" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform22" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface53" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform98" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface52" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform20" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface51" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform100" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface50" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform38" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface49" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform35" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface48" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform42" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface47" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform37" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface46" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform41" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface45" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform40" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface44" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform34" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface43" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform36" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface42" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform39" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface66" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform19" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface65" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform43" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface64" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform116" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface63" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform16" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface62" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform118" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface61" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform33" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface60" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform113" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface59" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform120" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface58" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform115" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface57" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform119" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface56" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform114" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface55" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform24" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface54" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform117" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface41" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform71" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface40" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform73" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface39" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform72" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface38" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform75" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface37" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform79" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface36" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform76" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface35" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform70" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface34" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform77" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface33" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform74" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface32" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform78" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface31" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform69" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface30" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform107" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface29" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform109" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface11" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform112" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface1" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform106" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface10" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform101" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface7" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform108" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface5" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform102" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface3" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform103" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface8" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform105" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface2" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform110" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface6" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform111" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface9" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform104" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface4" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform60" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface116" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform61" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface115" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform62" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface114" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform63" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface113" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform64" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface112" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform65" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface111" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform66" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface110" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform18" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface109" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform67" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface108" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform25" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface107" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform68" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface106" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform49" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface105" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform50" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface121" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform51" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface120" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform52" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface119" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform53" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface118" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform54" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface117" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform55" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface91" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform56" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface90" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform57" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface89" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform29" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface88" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform58" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface87" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform59" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface86" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform129" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface85" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform130" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface84" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform131" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface83" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform132" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface82" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform133" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface81" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform134" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface80" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform21" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface79" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform32" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface103" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform23" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface102" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform135" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface101" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform136" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface100" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform121" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface99" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform122" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface98" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform31" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface97" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform123" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface96" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform17" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface95" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform124" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface94" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform125" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface93" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform126" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface92" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform28" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface17" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform127" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface16" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform128" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface13" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform82" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface14" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform83" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface15" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform84" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface12" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform85" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface27" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform86" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface25" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform87" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface26" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform88" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface28" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform89" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface24" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform90" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface23" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform91" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface22" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform92" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface21" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform93" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface20" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform94" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface19" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform80" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface18" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform81" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface162" position={[0.49, -0.58, -1.59]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="polySurface169" position={[-0.86, -3.89, -21.73]}>
            <group name="transform95" position={[-48.01, 162.45, -36.43]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          </group>
        </group>
        <group name="polySurface170" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform96" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="polySurface172" rotation={[1.63, 0, 0]} scale={0.01}>
          <group name="polySurface171">
            <group name="transform140" position={[0, 0.23, -0.09]} rotation={[-1.63, 0, 0]} scale={100} />
            <mesh name="polySurface304" geometry={nodes.polySurface304.geometry} material={materials.pasted__lambert2} />
            <mesh name="polySurface305" geometry={nodes.polySurface305.geometry} material={materials.pasted__lambert2} />
            <mesh name="polySurface306" geometry={nodes.polySurface306.geometry} material={materials.pasted__lambert2} />
            <mesh name="polySurface406" geometry={nodes.polySurface406.geometry} material={materials.Tooner} />
          </group>
          <group name="transform139" position={[0, 0.23, -0.09]} rotation={[-1.63, 0, 0]} scale={100} />
          <mesh name="pCube1" geometry={nodes.pCube1.geometry} material={materials.Blur_effect} position={[0, 9.86, 0.55]} scale={14.59} />
          <mesh name="pCube10" geometry={nodes.pCube10.geometry} material={materials.lambert1} />
          <mesh name="pCube11" geometry={nodes.pCube11.geometry} material={materials.lambert1} />
          <mesh name="pCube4" geometry={nodes.pCube4.geometry} material={materials.Blur_effect} position={[0, 10.38, -0.84]} scale={9.32} />
          <mesh name="pCube9" geometry={nodes.pCube9.geometry} material={materials.lambert1} />
          <mesh name="polySurface173" geometry={nodes.polySurface173.geometry} material={materials.pasted__lambert2} position={[48.01, -162.45, 36.43]}>
            <mesh name="pCube7" geometry={nodes.pCube7.geometry} material={materials.lambert1} />
            <mesh name="polySurface407" geometry={nodes.polySurface407.geometry} material={materials.Tooner} position={[-48.01, 162.69, -36.52]} rotation={[-0.06, 0, 0]} />
          </mesh>
          <mesh name="polySurface174" geometry={nodes.polySurface174.geometry} material={materials.pasted__lambert2} position={[48.01, -162.45, 36.43]}>
            <mesh name="pCube6" geometry={nodes.pCube6.geometry} material={materials.lambert1} />
            <mesh name="polySurface408" geometry={nodes.polySurface408.geometry} material={materials.Tooner} position={[-48.01, 162.69, -36.52]} rotation={[-0.06, 0, 0]} />
          </mesh>
          <mesh name="polySurface182" geometry={nodes.polySurface182.geometry} material={materials.pasted__lambert2} position={[0, 0.23, -0.09]} rotation={[-0.06, 0, 0]}>
            <mesh name="polySurface161" geometry={nodes.polySurface161.geometry} material={materials.pasted__lambert2} position={[0, -0.24, 0.08]} rotation={[0.06, 0, 0]}>
              <mesh name="pCube5" geometry={nodes.pCube5.geometry} material={materials.lambert1} />
              <mesh name="polySurface411" geometry={nodes.polySurface411.geometry} material={materials.Tooner} position={[0, 0.23, -0.09]} rotation={[-0.06, 0, 0]} />
            </mesh>
            <mesh name="polySurface165" geometry={nodes.polySurface165.geometry} material={materials.pasted__lambert2} position={[-96.02, -0.27, 0.08]} rotation={[-3.08, 0, 0]} scale={-1}>
              <mesh name="pCube8" geometry={nodes.pCube8.geometry} material={materials.lambert1} />
              <group name="transform138" position={[-96.02, 0.27, -0.09]} rotation={[3.08, 0, 0]} scale={-1} />
              <mesh name="polySurface410" geometry={nodes.polySurface410.geometry} material={materials.Tooner} position={[-96.02, 0.27, -0.09]} rotation={[3.08, 0, 0]} scale={-1} />
            </mesh>
            <mesh name="polySurface409" geometry={nodes.polySurface409.geometry} material={materials.Tooner} />
          </mesh>
          <mesh name="polySurface187" geometry={nodes.polySurface187.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface188" geometry={nodes.polySurface188.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface189" geometry={nodes.polySurface189.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface190" geometry={nodes.polySurface190.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface191" geometry={nodes.polySurface191.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface192" geometry={nodes.polySurface192.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface193" geometry={nodes.polySurface193.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface194" geometry={nodes.polySurface194.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface195" geometry={nodes.polySurface195.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface196" geometry={nodes.polySurface196.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface197" geometry={nodes.polySurface197.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface198" geometry={nodes.polySurface198.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface199" geometry={nodes.polySurface199.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface200" geometry={nodes.polySurface200.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface201" geometry={nodes.polySurface201.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface202" geometry={nodes.polySurface202.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface203" geometry={nodes.polySurface203.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface204" geometry={nodes.polySurface204.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface205" geometry={nodes.polySurface205.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface206" geometry={nodes.polySurface206.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface207" geometry={nodes.polySurface207.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface208" geometry={nodes.polySurface208.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface209" geometry={nodes.polySurface209.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface210" geometry={nodes.polySurface210.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface211" geometry={nodes.polySurface211.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface212" geometry={nodes.polySurface212.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface213" geometry={nodes.polySurface213.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface214" geometry={nodes.polySurface214.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface215" geometry={nodes.polySurface215.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface216" geometry={nodes.polySurface216.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface217" geometry={nodes.polySurface217.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface218" geometry={nodes.polySurface218.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface219" geometry={nodes.polySurface219.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface220" geometry={nodes.polySurface220.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface221" geometry={nodes.polySurface221.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface222" geometry={nodes.polySurface222.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface223" geometry={nodes.polySurface223.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface224" geometry={nodes.polySurface224.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface225" geometry={nodes.polySurface225.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface226" geometry={nodes.polySurface226.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface227" geometry={nodes.polySurface227.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface228" geometry={nodes.polySurface228.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface229" geometry={nodes.polySurface229.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface230" geometry={nodes.polySurface230.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface231" geometry={nodes.polySurface231.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface232" geometry={nodes.polySurface232.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface233" geometry={nodes.polySurface233.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface234" geometry={nodes.polySurface234.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface235" geometry={nodes.polySurface235.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface236" geometry={nodes.polySurface236.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface237" geometry={nodes.polySurface237.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface238" geometry={nodes.polySurface238.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface239" geometry={nodes.polySurface239.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface240" geometry={nodes.polySurface240.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface241" geometry={nodes.polySurface241.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface242" geometry={nodes.polySurface242.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface243" geometry={nodes.polySurface243.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface244" geometry={nodes.polySurface244.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface245" geometry={nodes.polySurface245.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface246" geometry={nodes.polySurface246.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface247" geometry={nodes.polySurface247.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface248" geometry={nodes.polySurface248.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface249" geometry={nodes.polySurface249.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface250" geometry={nodes.polySurface250.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface251" geometry={nodes.polySurface251.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface252" geometry={nodes.polySurface252.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface253" geometry={nodes.polySurface253.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface254" geometry={nodes.polySurface254.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface255" geometry={nodes.polySurface255.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface256" geometry={nodes.polySurface256.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface257" geometry={nodes.polySurface257.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface258" geometry={nodes.polySurface258.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface259" geometry={nodes.polySurface259.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface260" geometry={nodes.polySurface260.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface261" geometry={nodes.polySurface261.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface262" geometry={nodes.polySurface262.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface263" geometry={nodes.polySurface263.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface264" geometry={nodes.polySurface264.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface265" geometry={nodes.polySurface265.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface266" geometry={nodes.polySurface266.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface267" geometry={nodes.polySurface267.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface268" geometry={nodes.polySurface268.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface269" geometry={nodes.polySurface269.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface270" geometry={nodes.polySurface270.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface271" geometry={nodes.polySurface271.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface272" geometry={nodes.polySurface272.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface273" geometry={nodes.polySurface273.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface274" geometry={nodes.polySurface274.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface275" geometry={nodes.polySurface275.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface276" geometry={nodes.polySurface276.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface277" geometry={nodes.polySurface277.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface278" geometry={nodes.polySurface278.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface279" geometry={nodes.polySurface279.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface280" geometry={nodes.polySurface280.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface281" geometry={nodes.polySurface281.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface282" geometry={nodes.polySurface282.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface283" geometry={nodes.polySurface283.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface284" geometry={nodes.polySurface284.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface285" geometry={nodes.polySurface285.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface286" geometry={nodes.polySurface286.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface287" geometry={nodes.polySurface287.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface288" geometry={nodes.polySurface288.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface289" geometry={nodes.polySurface289.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface290" geometry={nodes.polySurface290.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface291" geometry={nodes.polySurface291.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface292" geometry={nodes.polySurface292.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface293" geometry={nodes.polySurface293.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface294" geometry={nodes.polySurface294.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface295" geometry={nodes.polySurface295.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface296" geometry={nodes.polySurface296.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface297" geometry={nodes.polySurface297.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface298" geometry={nodes.polySurface298.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface299" geometry={nodes.polySurface299.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface300" geometry={nodes.polySurface300.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface301" geometry={nodes.polySurface301.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface302" geometry={nodes.polySurface302.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface303" geometry={nodes.polySurface303.geometry} material={materials.pasted__lambert2} />
          <mesh name="polySurface308" geometry={nodes.polySurface308.geometry} material={materials.Tooner} />
        </group>
        <group name="nucleus1" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="polySurface186" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="transform142" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
        <group name="nurbsCircle1" position={[0, 0, -0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12" geometry={nodes.pCube12.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle2" position={[-0.09, -0.05, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12001" geometry={nodes.pCube12001.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle3" position={[-0.07, 0.08, -0.17]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12002" geometry={nodes.pCube12002.geometry} material={materials.lambert1} position={[27.47, 25.69, -9.74]} scale={0} />
        </group>
        <group name="nurbsCircle4" position={[-0.19, 0.06, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12003" geometry={nodes.pCube12003.geometry} material={materials.lambert1} position={[27.47, 41.91, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle5" position={[-0.15, -0.17, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12004" geometry={nodes.pCube12004.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle6" position={[-0.24, -0.18, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12005" geometry={nodes.pCube12005.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle7" position={[-0.28, 0.08, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12006" geometry={nodes.pCube12006.geometry} material={materials.lambert1} position={[27.47, 50.26, -9.74]} scale={0} />
        </group>
        <group name="nurbsCircle8" position={[-0.4, 0.1, -0.13]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12007" geometry={nodes.pCube12007.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle9" position={[-0.48, 0.02, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12008" geometry={nodes.pCube12008.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle10" position={[-0.38, -0.11, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12009" geometry={nodes.pCube12009.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
        <group name="nurbsCircle11" position={[-0.46, -0.06, -0.17]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="pCube12010" geometry={nodes.pCube12010.geometry} material={materials.lambert1} position={[27.47, 36.19, -9.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        </group>
      </group>
    </group>
    </group>
  )
}

useGLTF.preload('/planep.glb')
